import { SlashCommandBuilder, MessageFlags } from 'discord.js';
import caller from '../API-calls.js';

const PC_POOL = [
    "Arya",
    "Onyx",
    "Éponine",
    "Gabrielle",
    "Guinevere",
    "Pragma",
    "Atrel",
    "Winnie",
    "Ranona",
]

const NPC_POOL = [
    "Laucian",
    "Kazmir",
    "Samira",
    "Valen",
    "Vesper",
    "Emeril",
    "Kaelus"

    //the ones below will be added later once we know more about them
    //"Terathi'in",
    //"The foreteller",
    //"Leonidas",
    //"Stellan",
    //"Evander",

]

const CHARACTER_RELATIONS = {
    //Sy
    "1290040130622591038": [
        "Arya",
        "Laucian",
        "Kazmir",
        "Samira",
        "Valen"
    ],

    //Cat
    "337426564121755649":[
        "Onyx",
        "Emeril",
        "Kaelus",
        "Leonidas",
        "Stellan",
    ],

    //Cam
    "323516007023116289":[
        "Éponine"
    ],

    //Nola
    "300012833016512514":[
        "Gabrielle",
        "Evander",
    ],

    //Jill
    "107285545180270592":[
        "Guinevere",
        "Pragma",
    ],

    //Jaz
    "422206294158475284":[
        "Atrel",
        "Ranona",
        "Vesper",
        "Terathi'in",
        "The foreteller",
    ],
}

const PROMPT_POOL = [
    //prompts written by Sy
    `That wasn't supposed to happen`,
    `I didn't think it would hurt this much`,
    `Say it again. slowly`,
    `That's not what you told me last time.`,
    `You promised.`,
    `Stay. Just for a minute.`,
    `I made this for you.`,
    `Do you hate me for it?`,
    `I can't fix this`,
    `I thought of you`,
    `I'll stay up with you.`,
    `You're terrible at this.`,

    //Nola
    `That wasn't me...`,

    //Prompts generated by AI
    `Don't look at me like that.`,
    `I never meant for you to find out.`,
    `You can let go now.`,
    `Tell me the truth.`,
    `I didn't know where else to go.`,
    `Please don't leave me here.`,
    `I thought you were dead.`,
    `I knew you'd come back.`,
    `You remembered.`,
    `You don't have to say anything.`,
    `Why didn't you tell me?`,
    `I tried to warn you.`,
    `I was so scared.`,
    `You look exhausted.`,
    `I can explain.`,
    `You shouldn't have come.`,
    `You came anyway.`,
    `I didn't want you to see this.`,
    `You were right.`,
    `I wish you were wrong.`,
    `Just this once.`,
    `I missed you.`,
    `I don't forgive you.`,
    `I forgive you.`,
    `Then why are you crying?`,
    `You don't get to do this.`,
    `I needed you.`,
    `You don't have to be afraid.`,
    `You make it sound so easy.`,
    `I've been waiting for you.`,
    `You weren't supposed to hear that.`,
    `I didn't mean it.`,
    `You know that's a lie.`,
    `Don't look at me like that.`,
    `Don't touch me.`,
    `I'm not going anywhere.`,
    `I thought this would make you happy.`,
    `I can't lose you too.`,
    `You don't owe me anything.`,
    `I shouldn't be here.`,
    `Then why did you come?`,
    `This is all I have left of you.`,
    `I don't want to fight anymore.`,
    `You're bleeding.`,
    `That's not my blood.`,
    `I know what you did.`,
    `No one else came.`,
    `I never asked you to save me.`,
    `You don't have to carry this alone.`,
    `You said you'd wait.`,
    `What happened to us?`,
    `I don't recognize this place anymore.`,
    `You remembered my favorite!`,
    `I wish things had been different.`,
    `I was trying to protect you.`,
    `You should really get some sleep.`,
    `You look like you're about to disappear.`,
    `You were never meant to see this side of me.`,
    `You don't have to pretend with me.`,
    `Don't say that.`,
    `I wish I had met you sooner.`,
    `I've never told anyone that before.`,
]

const AUTHORIZED_USERS = [
	"300012833016512514", //Nola
	"1290040130622591038",
]

function getRandomElement(array, pullCount = 1, omit = []){
    let selection = []

    for (let i = 0; i < omit.length; i++){
        array = array.filter(item => item !== omit[i])
    }

    for (let i = 0; i < pullCount; i++){
        let element = array[Math.floor(Math.random() * array.length)]
        if (element === undefined) continue
        selection.push(element)
        array = array.filter(item => item !== element)
    }

    return selection;
}

export default {
	data: new SlashCommandBuilder()
	.setName('dnd')
	.setDescription('Manage overseer bot.')
	.addSubcommand(subCommand =>
		subCommand
			.setName('passwd')
			.setDescription('Set account password for Overseer Bot.')
			.addStringOption(option =>
	        	option
	        		.setName('p')
	        		.setDescription('The new password.')
	        		.setRequired(true)
	        )
	).addSubcommand(subCommand =>
		subCommand
		.setName('set-group')
		.setDescription('Set the group of the channel the command is executed in.')
		.addStringOption(option =>
        	option
        		.setName('n')
        		.setDescription('The name of the chapter group.')
        		.setRequired(true)
        )
	)
	.addSubcommand(subCommand =>
		subCommand
		.setName('track-channel')
		.setDescription('Add this channel to the tracked channel list.')
	)
	.addSubcommand(subCommand =>
		subCommand
		.setName('forced-refresh')
		.setDescription('Make the bot scan the channels ahead of schedule.')
	)
	.addSubcommand(subCommand =>
		subCommand
		.setName('url')
		.setDescription("Get a link to the guild's campaign.")
	)
    .addSubcommand(subCommand =>
        subCommand
        .setName('get-prompt')
        .setDescription("Get a prompt, along with characters to use.")
        .addBooleanOption(option =>
            option
            .setName("add-npcs")
            .setDescription("(True: Add characters like Samira, Kaz, etc to the selection pool.")
            .setRequired(false)
        )
        .addBooleanOption(option =>
            option
            .setName("include-own-pc")
            .setDescription("True: additionally draw one of your own characters. (not in character count)")
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option
            .setName('character-count')
            .setDescription("Select <this many> characters for the cast.")
            .setRequired(false)
        )

    ),
	async execute (interaction) {
		const user = interaction.member.user;
		const sub = interaction.options.getSubcommand();
		const guild = interaction.guild
		const channel = interaction.channel

		if (sub === "passwd"){
			return await caller.Reply(interaction, "Command not implemented yet.")
			caller.UpdatePassword(user.id, user.username, interaction.options.getString("p"))
		}
		else if (sub === "set-group") {
			return await caller.Reply(interaction, "Command not implemented yet.")

			let campaign = caller.GetGuildCampaign(guild.id)
			if (campaign.response){ console.log(campaign.response); caller.Reply(interaction, "Could not create the chapter group: "+campaign.response) }
			let name = interaction.options.getString("n")
			let chapter = await GetChapterFromChannelAndGuild(campaign.id, channel.id)

			if (chapter.response) { console.log(chapter.response); caller.Reply(interaction, "Could not create the chapter group: "+chapter.response) }

			await caller.CreateChapterGroup(name, campaign.id)

			let chapterGroup = await GetChapterGroupFromGuildAndName(campaign.id, name)
			//chapter group should exist, provided the API works.

			await caller.UpdateChapterToGroupRelation(chapterGroup.id, chapter.id)
		}
		else if (sub === "track-channel"){
			if (!AUTHORIZED_USERS.includes(user.id)){
				return await caller.Reply(interaction, "You are not authorized to use this command.")
			}

			let campaign = await caller.GetGuildCampaign(guild.id)
			if (campaign.response){ console.log(campaign.response); return await caller.Reply(interaction, "Could not create the chapter: "+campaign.response) }
			if (!campaign){ console.log("Could not fetch campaign"); return await caller.Reply(interaction, "Could not create the chapter.") }

			await caller.CreateChapter(channel.name, 1, channel.id, campaign.id, 0)
			await caller.Reply(interaction, "Success.")

		}
		else if (sub === "forced-refresh"){
			if (!AUTHORIZED_USERS.includes(user.id)){
				return await caller.Reply(interaction, "You are not authorized to use this command.")
			}
			await caller.deferReply(interaction, "Logging...")

			await caller.LogNewMessages(interaction.client)
			return await caller.editDeferReply(interaction, "success")
		}
		else if (sub === "url"){
			return await caller.Reply(interaction, "[nolar-eclipse.ca](https://nolar-eclipse.ca/?guild="+guild.id+")")
		}
        else if (sub === "get-prompt"){
            const addNPCs = interaction.options.getBoolean('add-npcs') ?? false
            const includeOwnPc = interaction.options.getBoolean('include-own-pc') ?? false
            const pickCount = interaction.options.getInteger('character-count') ?? 1



            if (pickCount < 0) pickCount = 0

            let charaPool = [...PC_POOL]

            if (addNPCs) charaPool.push(...NPC_POOL)

            let characters = getRandomElement(charaPool, pickCount, CHARACTER_RELATIONS[user.id] ?? [])




            let prompt = getRandomElement(PROMPT_POOL, 1)[0]


            let pcLine = ""
            if (includeOwnPc) {
                let pc = getRandomElement(CHARACTER_RELATIONS[user.id], 1)[0]

                pcLine += "\n Your PC: `" + pc + "`"
            }


            let msg = `## Your prompt:\n\n`

            msg += '> "'+prompt+'"\n\n'

            if (characters.length == 1) msg += 'Selected character: ' + characters[0]
            else if(characters.length < 1) {/* nothing */}
            else{
                msg += 'Selected characters:\n'
                for (let i = 0; i < characters.length; i++){
                    msg += '`'+characters[i]+'`\n'
                }
            }

            msg += pcLine

            return await caller.Reply(interaction, msg)
        }
	}
};