import { SlashCommandBuilder, MessageFlags } from 'discord.js';
import caller from '../API-calls.js';
import entries from '../entries.js'


const PC_POOL = [
    "Arya",
    "Onyx",
    "Éponine",
    "Gabrielle",
    "Guinevere",
    "Pragma",
    "Atrel",
    "Winnie",
    "Ranona",
]

const NPC_POOL = [
    "Laucian",
    "Kazmir",
    "Samira",
    "Valen",
    "Vesper",
    "Emeril",
    "Kaelus"

    //the ones below will be added later once we know more about them
    //"Terathi'in",
    //"The foreteller",
    //"Leonidas",
    //"Stellan",
    //"Evander",

]

const CHARACTER_RELATIONS = {
    //Sy
    "1290040130622591038": [
        "Arya",
        "Laucian",
        "Kazmir",
        "Samira",
        "Valen"
    ],

    //Cat
    "337426564121755649":[
        "Onyx",
        "Emeril",
        "Kaelus",
        "Leonidas",
        "Stellan",
    ],

    //Cam
    "323516007023116289":[
        "Éponine"
    ],

    //Nola
    "300012833016512514":[
        "Gabrielle",
        "Evander",
    ],

    //Jill
    "107285545180270592":[
        "Guinevere",
        "Pragma",
    ],

    //Jaz
    "422206294158475284":[
        "Atrel",
        "Ranona",
        "Vesper",
        "Terathi'in",
        "The foreteller",
    ],
}

const PROMPT_POOL = [
    //prompts written by Sy
    `That wasn't supposed to happen`,
    `I didn't think it would hurt this much`,
    `Say it again. slowly`,
    `That's not what you told me last time.`,
    `You promised.`,
    `Stay. Just for a minute.`,
    `I made this for you.`,
    `Do you hate me for it?`,
    `I can't fix this`,
    `I thought of you`,
    `I'll stay up with you.`,
    `You're terrible at this.`,

    //prompts written by Nola
    `That wasn't me...`,

    //Prompts generated by AI
    `Don't look at me like that.`,
    `I never meant for you to find out.`,
    `You can let go now.`,
    `Tell me the truth.`,
    `I didn't know where else to go.`,
    `Please don't leave me here.`,
    `I thought you were dead.`,
    `I knew you'd come back.`,
    `You remembered.`,
    `You don't have to say anything.`,
    `Why didn't you tell me?`,
    `I tried to warn you.`,
    `I was so scared.`,
    `You look exhausted.`,
    `I can explain.`,
    `You shouldn't have come.`,
    `You came anyway.`,
    `I didn't want you to see this.`,
    `You were right.`,
    `I wish you were wrong.`,
    `Just this once.`,
    `I missed you.`,
    `I don't forgive you.`,
    `I forgive you.`,
    `Then why are you crying?`,
    `You don't get to do this.`,
    `I needed you.`,
    `You don't have to be afraid.`,
    `You make it sound so easy.`,
    `I've been waiting for you.`,
    `You weren't supposed to hear that.`,
    `I didn't mean it.`,
    `You know that's a lie.`,
    `Don't look at me like that.`,
    `Don't touch me.`,
    `I'm not going anywhere.`,
    `I thought this would make you happy.`,
    `I can't lose you too.`,
    `You don't owe me anything.`,
    `I shouldn't be here.`,
    `Then why did you come?`,
    `This is all I have left of you.`,
    `I don't want to fight anymore.`,
    `You're bleeding.`,
    `That's not my blood.`,
    `I know what you did.`,
    `No one else came.`,
    `I never asked you to save me.`,
    `You don't have to carry this alone.`,
    `You said you'd wait.`,
    `What happened to us?`,
    `I don't recognize this place anymore.`,
    `You remembered my favorite!`,
    `I wish things had been different.`,
    `I was trying to protect you.`,
    `You should really get some sleep.`,
    `You look like you're about to disappear.`,
    `You were never meant to see this side of me.`,
    `You don't have to pretend with me.`,
    `Don't say that.`,
    `I wish I had met you sooner.`,
    `I've never told anyone that before.`,

    //prompts written by Jaz
    "why does it matter to you?"
    ,"then prove it."
    ,"twice in one day? isn't that a bit much?"
    ,"don't they make some kind of medication for that?"
    ,"you're much tougher than you look."
    ,"please don't tell anyone i said that."
    ,"what's done is done, right?"
    ,"i'd appreciate a break."
    ,"where have you been all night?"
    ,"i wish you believed me."
    ,"i feel much safer with you here."
    ,"can we please forget about that?"
    ,"none of that matters to me."
    ,"i'd prefer if we spoke. . .in private."
    ,"i wasn't holding out for an apology."
    ,"i've made peace with not knowing."
    ,"do you hear yourself?"
    ,"how did you get that?"
    ,"what you're doing. . . it's wrong."
    ,"please pretend."
    ,"no. no. no. i can't be around that."
    ,"it was more than a white lie."
    ,"your smile is contagious to me."
    ,"don't you ever want to disappear?"
    ,"i've been waiting to hear from you."
    ,"so what?"
    ,"and if it's true?"
    ,"that doesn't concern you."
    ,"let's wrap this up."
    ,"the water's so cold."
    ,"you hide it well."
    ,"i can't look at you like this."
    ,"how could you destroy all the evidence of us?"
    ,"you have no idea, do you?"
    ,"i thought worse of you. i'm sorry."
    ,"i thought better of you. i'm sorry."
    ,"i need a moment to collect myself."
    ,"who do you think you are?"
    ,"who do you think i am?"
    ,"i don't deserve this."
    ,"i want you to think this through."
    ,"you stress me out."
    ,"(s)he doesn't look at anyone like that."
    ,"(s)he'd do anything for you."
    ,"i was worried you assumed that."
    ,"can i please?"
    ,"look me in the eye and say it."
    ,"what happened to the person i knew?"
    ,"can we stay here?"
    ,"don't talk. i'll show you."
    ,"you're not finished, are you?"
    ,"your touch is. . . softer than anticipated."
    ,"i'm starved."
    ,"please. be gentle."
    ,"it doesn't matter what i say, does it?"
    ,"why did it have to be you?"
    ,"silvertongued as usual, i see."
    ,"if it means that much to you. . ."
    ,"i'm rather particular."
    ,"it's not a good idea to look at me like that."
    ,"am i supposed to act grateful?"
    ,"i can't stand to lose you again."
    ,"do you think that matters to me?"
    ,"when have i ever told you no?"
    ,"you're quite a troublemaker."
    ,"i didn't expect this from you."
    ,"by god, how much have you had to drink?"
    ,"i had a dream about you."
    ,"you have too much control over me."
    ,"i didn't know you were capable of that."
    ,"we'll talk later."
    ,"i'm not accepting criticism, thank you."
    ,"don't waste your time on me."
    ,"can we try again?"
    ,"how did you know it's my favorite?"
    ,"okay, now i'm begging."
    ,"you're the only one whose opinion i trust."
    ,"i don't care what you think of me right now."
    ,"lie down for me."
    ,"you're the best thing about this place."
    ,"i've been waiting years for those words."
    ,"no. if i hated you, you'd know."
    ,"you weren't supposed to give up on me."
    ,"believe me. it was a mistake."
    ,"i'd love nothing more than to cook dinner with you."
    ,"i would never let that happen."
    ,"you have to relax for this to work."
    ,"how do i make you trust me?"
    ,"are you taking notes yet?"
    ,"i was up all night thinking about this moment."
    ,"the sun suits you.", "the moon suits you."
    ,"i need your help."
    ,"just eat it."
    ,"in other circumstances, i would have more patience."
    ,"you're soaking wet."
    ,"you're braver than me."
    ,"ask me if i care. i do."
    ,"i need to hear you say that again."
    ,"i didn't expect you to be anything other than difficult."
    ,"i'll never recover from you, you know.",
]

const AUTHORIZED_USERS = [
	"300012833016512514", //Nola
	"1290040130622591038",
]

function getRandomElement(array, pullCount = 1, omit = []){
    let selection = []

    for (let i = 0; i < omit.length; i++){
        array = array.filter(item => item !== omit[i])
    }

    for (let i = 0; i < pullCount; i++){
        let element = array[Math.floor(Math.random() * array.length)]
        if (element === undefined) continue
        selection.push(element)
        array = array.filter(item => item !== element)
    }

    return selection;
}

function formatName(string) {
    string = string.toLowerCase()
    return string.charAt(0).toUpperCase() + string.slice(1);
}

export default {
	data: new SlashCommandBuilder()
	.setName('dnd')
	.setDescription('Manage overseer bot.')
	.addSubcommand(subCommand =>
		subCommand
			.setName('passwd')
			.setDescription('Set account password for Overseer Bot.')
			.addStringOption(option =>
	        	option
	        		.setName('p')
	        		.setDescription('The new password.')
	        		.setRequired(true)
	        )
	).addSubcommand(subCommand =>
		subCommand
		.setName('set-group')
		.setDescription('Set the group of the channel the command is executed in.')
		.addStringOption(option =>
        	option
        		.setName('n')
        		.setDescription('The name of the chapter group.')
        		.setRequired(true)
        )
	)
	.addSubcommand(subCommand =>
		subCommand
		.setName('track-channel')
		.setDescription('Add this channel to the tracked channel list.')
	)
	.addSubcommand(subCommand =>
		subCommand
		.setName('forced-refresh')
		.setDescription('Make the bot scan the channels ahead of schedule.')
	)
	.addSubcommand(subCommand =>
		subCommand
		.setName('url')
		.setDescription("Get a link to the guild's campaign.")
	)
    .addSubcommand(subCommand =>
        subCommand
        .setName('get-prompt')
        .setDescription("Get a prompt, along with characters to use.")
        .addBooleanOption(option =>
            option
            .setName("add-npcs")
            .setDescription("True: Add characters like Samira, Kaz, etc to the selection pool.")
            .setRequired(false)
        )
        .addBooleanOption(option =>
            option
            .setName("include-own-pc")
            .setDescription("True: additionally draw one of your own characters. (not in character count)")
            .setRequired(false)
        )
        .addIntegerOption(option =>
            option
            .setName('character-count')
            .setDescription("Select <this many> characters for the cast.")
            .setRequired(false)
        )
        .addBooleanOption(option =>
            option
            .setName("disable-ephemeral")
            .setDescription("True: Send the message for everyone, so that anyone can see the prompt.")
            .setRequired(false)
        )
    )
    .addSubcommand(subCommand =>
        subCommand
        .setName('bestiary')
        .setDescription('Browse Valmora\'s bestiary.')
        .addStringOption( option => 
            option
            .setName('query')
            .setDescription('Search for a specific beast. leave empty to show a list of all the beasts.')
            .setRequired(false)
        )
    ),
	async execute (interaction) {
		const user = interaction.member.user;
		const sub = interaction.options.getSubcommand();
		const guild = interaction.guild
		const channel = interaction.channel

		if (sub === "passwd"){
			return await caller.Reply(interaction, "Command not implemented yet.")
			caller.UpdatePassword(user.id, user.username, interaction.options.getString("p"))
		}
		else if (sub === "set-group") {
			return await caller.Reply(interaction, "Command not implemented yet.")

			let campaign = caller.GetGuildCampaign(guild.id)
			if (campaign.response){ console.log(campaign.response); caller.Reply(interaction, "Could not create the chapter group: "+campaign.response) }
			let name = interaction.options.getString("n")
			let chapter = await GetChapterFromChannelAndGuild(campaign.id, channel.id)

			if (chapter.response) { console.log(chapter.response); caller.Reply(interaction, "Could not create the chapter group: "+chapter.response) }

			await caller.CreateChapterGroup(name, campaign.id)

			let chapterGroup = await GetChapterGroupFromGuildAndName(campaign.id, name)
			//chapter group should exist, provided the API works.

			await caller.UpdateChapterToGroupRelation(chapterGroup.id, chapter.id)
		}
		else if (sub === "track-channel"){
			if (!AUTHORIZED_USERS.includes(user.id)){
				return await caller.Reply(interaction, "You are not authorized to use this command.")
			}

			let campaign = await caller.GetGuildCampaign(guild.id)
			if (campaign.response){ console.log(campaign.response); return await caller.Reply(interaction, "Could not create the chapter: "+campaign.response) }
			if (!campaign){ console.log("Could not fetch campaign"); return await caller.Reply(interaction, "Could not create the chapter.") }

			await caller.CreateChapter(channel.name, 1, channel.id, campaign.id, 0)
			await caller.Reply(interaction, "Success.")

		}
		else if (sub === "forced-refresh"){
			if (!AUTHORIZED_USERS.includes(user.id)){
				return await caller.Reply(interaction, "You are not authorized to use this command.")
			}
			await caller.deferReply(interaction, "Logging...")

			await caller.LogNewMessages(interaction.client)
			return await caller.editDeferReply(interaction, "success")
		}
		else if (sub === "url"){
			return await caller.Reply(interaction, "[nolar-eclipse.ca](https://nolar-eclipse.ca/?guild="+guild.id+")")
		}
        else if (sub === "get-prompt"){
            const addNPCs = interaction.options.getBoolean('add-npcs') ?? false
            const includeOwnPc = interaction.options.getBoolean('include-own-pc') ?? false
            const pickCount = interaction.options.getInteger('character-count') ?? 1
            const disableEphemeral = interaction.options.getBoolean('disable-ephemeral') ?? false



            if (pickCount < 0) pickCount = 0

            let charaPool = [...PC_POOL]

            if (addNPCs) charaPool.push(...NPC_POOL)

            let characters = getRandomElement(charaPool, pickCount, CHARACTER_RELATIONS[user.id] ?? [])




            let prompt = getRandomElement(PROMPT_POOL, 1)[0]


            let pcLine = ""
            if (includeOwnPc) {
                let pc = getRandomElement(CHARACTER_RELATIONS[user.id], 1)[0]

                pcLine += "\n Your character: `" + pc + "`"
            }


            let msg = `## Your prompt:\n\n`

            msg += '> "'+prompt+'"\n\n'

            if (characters.length == 1) msg += 'Selected character: `' + characters[0] + '`'
            else if(characters.length < 1) {/* nothing */}
            else{
                msg += 'Selected characters:\n'
                for (let i = 0; i < characters.length; i++){
                    msg += '`'+characters[i]+'`\n'
                }
            }

            msg += pcLine

            return await caller.Reply(interaction, msg, !disableEphemeral)
        }
        else if (sub === "bestiary"){
            let query = interaction.options.getString("query") ?? ""
            if (query == "") {
                let keys = Object.keys(entries.bestiary)
                keys.sort()
                let concatenatedString = "## The beasts of Valmora:\n\n"
                for (let i = 0; i < keys.length; i++){
                    concatenatedString += "`"+keys[i]+"`\n"
                }
                return await caller.Reply(interaction, concatenatedString)
            }
            else{
                let entry = entries.bestiary[formatName(query)] ?? `## No creature with name '`+query+`' found.\ntry using \`/dnd bestiary\` for a list of all the beasts.`
                
                return await caller.Reply(interaction, entry)
            }
        }
	}
};